repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the ref you want to point at
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: detect-private-key
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
    -   id: docker-compose-check
-   repo: https://github.com/hadolint/hadolint
    rev: v1.22.1
    hooks:
    -   id: hadolint
    -   id: hadolint-docker
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: v2.1.5
    hooks:
    -   id: markdownlint
